# Generated by Django 5.2.5 on 2025-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
