# Generated by Django 5.2.5 on 2025-08-30 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_best_selling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='best_selling',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='best_selling',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
