# Generated by Django 5.2.5 on 2025-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pants',
            name='name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
    ]
